In [286]:
import numpy as np
set_printoptions(precision=4, suppress=True)

# 1. Write a Python program to compute the eigenvalues and right eigenvectors of a given square array

In [304]:
def eigenvector_value(matrx):
    if np.shape(matrx)[0] != np.shape(matrx)[1]:
        return ("Function takes only Square Matrices")
    else:
        eig_value,eig_vector = np.linalg.eig(np.array(matrx))
        print('Eigenvectors \n%s' %eig_vector)
        print('Eigenvalues \n%s' %eig_value)
    
    

Illustration

In [305]:
A = np.random.randint(10, size=(3,3))
B = np.random.randint(10, size=(3,2))


In [306]:
eigenvector_value(A)

Eigenvectors 
[[-0.3927 -0.7366 -0.78  ]
 [-0.8394  0.6557 -0.116 ]
 [-0.3758  0.1658  0.615 ]]
Eigenvalues 
[11.8361  0.5346 -2.3707]


In [307]:
eigenvector_value(B)

'Function takes only Square Matrices'

# 2.  Write a Python program to compute the factor of a given array by Singular Value Decomposition

In [308]:
def single_value_decomp(matrx):
    U,Sigma,V=svd(matrx)
    print('First orthogonal \n%s' %U)
    print('Sigma \n%s' %Sigma)
    print('Second orthogonal \n%s' %V)
  

Illustration

In [309]:
single_value_decomp(A)

First orthogonal 
[[-0.5035  0.7095  0.493 ]
 [-0.8152 -0.2011 -0.5431]
 [-0.2862 -0.6754  0.6797]]
Sigma 
[14.5952  3.1421  0.3271]
Second orthogonal 
[[-0.4974 -0.3726 -0.7834]
 [-0.3515 -0.7391  0.5747]
 [ 0.7931 -0.5612 -0.2367]]


# 3.  Write a Python program to compute the determinant of an array.

In [310]:
def determinant(matrx):
    matrx = np.array(matrx)
    if np.shape(matrx)[0] != np.shape(matrx)[1]:
        return ("Function takes only Square Matrices")
    return round(np.linalg.det(matrx),4)

Illustration

In [311]:
determinant(A)

-15.0

In [312]:
determinant(B)

'Function takes only Square Matrices'